/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenderRouteImport } from './routes/gender'
import { Route as CustomizeGenderRouteImport } from './routes/customize.$gender'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenderRoute = GenderRouteImport.update({
  id: '/gender',
  path: '/gender',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeGenderRoute = CustomizeGenderRouteImport.update({
  id: '/customize/$gender',
  path: '/customize/$gender',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gender': typeof GenderRoute
  '/customize/$gender': typeof CustomizeGenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gender': typeof GenderRoute
  '/customize/$gender': typeof CustomizeGenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gender': typeof GenderRoute
  '/customize/$gender': typeof CustomizeGenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gender' | '/customize/$gender'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gender' | '/customize/$gender'
  id: '__root__' | '/' | '/gender' | '/customize/$gender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenderRoute: typeof GenderRoute
  CustomizeGenderRoute: typeof CustomizeGenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gender': {
      id: '/gender'
      path: '/gender'
      fullPath: '/gender'
      preLoaderRoute: typeof GenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize/$gender': {
      id: '/customize/$gender'
      path: '/customize/$gender'
      fullPath: '/customize/$gender'
      preLoaderRoute: typeof CustomizeGenderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenderRoute: GenderRoute,
  CustomizeGenderRoute: CustomizeGenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
